#include "aether/src/browser/webui/aether_chrome_ui.h"

#include <memory>
#include <string>

#include "chrome/browser/profiles/profile.h"
#include "chrome/browser/ui/browser_finder.h"
#include "aether/src/browser/webui/handlers/aether_window_controls_handler.h"
#include "content/public/browser/web_ui.h"
#include "content/public/browser/web_ui_data_source.h"

// Generated grit resource headers.
#include "chrome/grit/aether_webui_test_resources.h"
#include "chrome/grit/aether_webui_test_resources_map.h"

namespace {

void CreateAndAddAetherChromeDataSource(Profile* profile) {
  content::WebUIDataSource* source =
      content::WebUIDataSource::CreateAndAdd(profile, "aether-chrome");

  source->DisableContentSecurityPolicy();

  // Add the resource path mapping generated by GRIT
  source->AddResourcePaths(
      base::make_span(kAetherWebuiTestResources, kAetherWebuiTestResourcesSize));

  // Set the default resource index.html
  source->SetDefaultResource(IDR_AETHER_WEBUI_TEST_INDEX_HTML);
}

}  // namespace

AetherChromeUI::AetherChromeUI(content::WebUI* web_ui)
    : TopChromeWebUIController(web_ui) {
  CreateAndAddAetherChromeDataSource(Profile::FromWebUI(web_ui));
  Browser* browser = chrome::FindBrowserWithWebContents(web_ui->GetWebContents());
  if (browser) {
    navigation_handler_ = std::make_unique<AetherNavigationHandler>(browser);
  }
}

AetherChromeUI::~AetherChromeUI() = default;

void AetherChromeUI::BindInterface(
    mojo::PendingReceiver<aether::mojom::WindowControls> receiver) {
  Browser* browser = chrome::FindBrowserWithWebContents(web_ui()->GetWebContents());
  window_controls_handler_ = std::make_unique<AetherWindowControlsHandler>(
      std::move(receiver), browser);
}

void AetherChromeUI::BindInterface(
    mojo::PendingReceiver<aether::mojom::TabManager> receiver) {
  Browser* browser = chrome::FindBrowserWithWebContents(web_ui()->GetWebContents());
  if (!tab_manager_handler_) {
    tab_manager_handler_ = std::make_unique<AetherTabManagerHandler>(
        browser, browser->tab_strip_model());
  }
  tab_manager_handler_->BindReceiver(std::move(receiver));
}

void AetherChromeUI::BindInterface(
    mojo::PendingReceiver<aether::mojom::NavigationHandler> receiver) {
  if (navigation_handler_) {
    navigation_handler_->BindReceiver(std::move(receiver));
  }
}

