#include "aether/src/browser/webui/aether_webui_test_ui.h"

#include <memory>
#include <string>

#include "chrome/browser/profiles/profile.h"
#include "content/public/browser/web_ui.h"
#include "content/public/browser/web_ui_data_source.h"

// Generated grit resource headers.
// These headers are produced by the GRIT compiler from the .grd resource mapping.
#include "chrome/grit/aether_webui_test_resources.h"
#include "chrome/grit/aether_webui_test_resources_map.h"

namespace {

void CreateAndAddAetherWebUIDataSource(Profile* profile) {
  content::WebUIDataSource* source =
      content::WebUIDataSource::CreateAndAdd(profile, "aether-webui");

  // Disable CSP for the test page to prevent security policy load blocks.
  source->DisableContentSecurityPolicy();

  // Add the resource path mapping generated by GRIT
  source->AddResourcePaths(
      base::make_span(kAetherWebuiTestResources, kAetherWebuiTestResourcesSize));

  // Set the default resource index.html
  source->SetDefaultResource(IDR_AETHER_WEBUI_TEST_INDEX_HTML);
}

}  // namespace

AetherWebUITestUI::AetherWebUITestUI(content::WebUI* web_ui)
    : content::WebUIController(web_ui) {
  CreateAndAddAetherWebUIDataSource(Profile::FromWebUI(web_ui));
}

AetherWebUITestUI::~AetherWebUITestUI() = default;
