# Aether Browser — Generate Identity Patch from Live Source
# Reads the Brave source, applies Aether branding changes, and generates
# a verified patch file that replaces tools/patches/0001-aether-identity.patch.
# Usage: generate-identity-patch.ps1

$ErrorActionPreference = "Stop"

$BraveSrc = if ($env:BRAVE_SRC) { $env:BRAVE_SRC } else { "C:\src\brave-browser" }
$chromiumSrc = Join-Path $BraveSrc "src"
$repoRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$patchOutput = Join-Path $repoRoot "tools\patches\0001-aether-identity.patch"

if (-not (Test-Path $chromiumSrc)) {
    Write-Host "[FAIL] Brave source not found at $chromiumSrc" -ForegroundColor Red
    Write-Host "Clone Brave first. See docs/development/FIRST_BUILD_CHECKLIST.md" -ForegroundColor Yellow
    exit 1
}

Write-Host "==================================================" -ForegroundColor Cyan
Write-Host "    Aether Identity Patch Generator                " -ForegroundColor Cyan
Write-Host "==================================================" -ForegroundColor Cyan

# Define all branding replacements
$replacements = @(
    @{ File = "brave\app\theme\brave\BRANDING"; Old = "COMPANY_FULLNAME=Brave Software Inc."; New = "COMPANY_FULLNAME=Aether" },
    @{ File = "brave\app\theme\brave\BRANDING"; Old = "COMPANY_SHORTNAME=BraveSoftware"; New = "COMPANY_SHORTNAME=Aether" },
    @{ File = "brave\app\theme\brave\BRANDING"; Old = "PRODUCT_FULLNAME=Brave Browser"; New = "PRODUCT_FULLNAME=Aether Browser" },
    @{ File = "brave\app\theme\brave\BRANDING"; Old = "PRODUCT_SHORTNAME=Brave-Browser"; New = "PRODUCT_SHORTNAME=Aether-Browser" },
    @{ File = "brave\app\theme\brave\BRANDING"; Old = "PRODUCT_INSTALLER_FULLNAME=Brave"; New = "PRODUCT_INSTALLER_FULLNAME=Aether" },
    @{ File = "brave\app\theme\brave\BRANDING"; Old = "APP_SPECIFIC_CATALOG_NAME=BraveSoftware"; New = "APP_SPECIFIC_CATALOG_NAME=Aether" }
)

Push-Location $chromiumSrc

# Verify the source files exist
$filesToPatch = $replacements | ForEach-Object { $_.File } | Sort-Object -Unique
foreach ($file in $filesToPatch) {
    if (-not (Test-Path $file)) {
        Write-Host "[FAIL] Expected file not found: $file" -ForegroundColor Red
        Write-Host "The Brave source structure may have changed. Manual investigation required." -ForegroundColor Yellow
        Pop-Location
        exit 1
    }
    Write-Host "[FOUND] $file" -ForegroundColor Green
}

# Ensure clean state
$status = & git status --porcelain $filesToPatch
if ($status) {
    Write-Host "[FAIL] The following files have uncommitted changes:" -ForegroundColor Red
    Write-Host $status -ForegroundColor Red
    Write-Host "Reset these files before generating the patch: git checkout -- <files>" -ForegroundColor Yellow
    Pop-Location
    exit 1
}

# Apply changes
Write-Host "`nApplying branding changes..." -ForegroundColor Green
foreach ($r in $replacements) {
    $filePath = $r.File
    $content = Get-Content $filePath -Raw
    if ($content.Contains($r.Old)) {
        $content = $content.Replace($r.Old, $r.New)
        Set-Content -Path $filePath -Value $content -NoNewline
        Write-Host "  Replaced in $($filePath): $($r.Old) -> $($r.New)" -ForegroundColor Cyan
    } else {
        Write-Host "  [WARN] Pattern not found in $($filePath): $($r.Old)" -ForegroundColor Yellow
    }
}

# Also handle brave_strings.grd if it exists
$grdFile = "brave\app\brave_strings.grd"
if (Test-Path $grdFile) {
    $grdContent = Get-Content $grdFile -Raw
    $grdContent = $grdContent -replace '(?<=<message name="IDS_PRODUCT_NAME"[^>]*>\s*)Brave(?=\s*</message>)', 'Aether'
    $grdContent = $grdContent -replace '(?<=<message name="IDS_SHORT_PRODUCT_NAME"[^>]*>\s*)Brave(?=\s*</message>)', 'Aether'
    Set-Content -Path $grdFile -Value $grdContent -NoNewline
    Write-Host "  Updated IDS_PRODUCT_NAME in $grdFile" -ForegroundColor Cyan
}

# Generate the patch
Write-Host "`nGenerating unified diff..." -ForegroundColor Green
$diff = & git diff $filesToPatch $grdFile 2>&1
if (-not $diff) {
    Write-Host "[FAIL] No diff generated. Changes may not have been applied correctly." -ForegroundColor Red
    Pop-Location
    exit 1
}

# Write patch header and diff content
$patchHeader = @"
From: Aether Team <dev@aetherbrowser.org>
Date: $(Get-Date -Format "ddd, dd MMM yyyy HH:mm:ss K")
Subject: [PATCH 0001] feat(identity): rename Brave to Aether in product branding

Renames all user-visible instances of "Brave" to "Aether" in the core
branding and string resource files. This patch establishes Aether as a
distinct product identity built on the Brave/Chromium foundation.

Auto-generated by tools/scripts/generate-identity-patch.ps1
---
"@

$patchContent = "$patchHeader`n$diff`n-- `n2.54.0`n"
Set-Content -Path $patchOutput -Value $patchContent -NoNewline

Write-Host "[PASS] Patch written to: $patchOutput" -ForegroundColor Green

# Reset the source tree
Write-Host "Resetting Brave source to clean state..." -ForegroundColor Yellow
& git checkout -- $filesToPatch $grdFile

# Verify the patch applies cleanly
Write-Host "Verifying patch applies cleanly..." -ForegroundColor Green
$checkResult = & git apply --check $patchOutput 2>&1
if ($LASTEXITCODE -eq 0) {
    Write-Host "[PASS] Patch verified: git apply --check passed." -ForegroundColor Green
} else {
    Write-Host "[FAIL] Patch verification failed:" -ForegroundColor Red
    Write-Host $checkResult -ForegroundColor Red
}

Pop-Location

Write-Host "`n==================================================" -ForegroundColor Cyan
Write-Host "Patch generation complete." -ForegroundColor Green
Write-Host "File: $patchOutput" -ForegroundColor Cyan
Write-Host "==================================================" -ForegroundColor Cyan

exit 0
