import("//mojo/public/tools/bindings/mojom.gni")
import("//ui/webui/webui_features.gni")

assert(is_linux || is_chromeos || is_win || is_mac)
assert(!is_fuchsia, "Fuchsia shouldn't use anything in //chrome")

mojom("aether_tab_manager_mojom") {
  sources = [ "tab_manager.mojom" ]
  public_deps = [
    "//components/tab_groups/public/mojom:mojo_bindings",
    "//components/tabs/public/mojom",
    "//mojo/public/mojom/base",
    "//url/mojom:url_mojom_gurl",
  ]
  webui_module_path = "/"
}

mojom("aether_window_controls") {
  sources = [
    "window_controls.mojom",
  ]

  public_deps = [
    "//mojo/public/mojom/base",
  ]

  webui_module_path = "/"
}

mojom("aether_navigation_mojom") {
  sources = [
    "navigation.mojom",
  ]

  public_deps = [
    "//mojo/public/mojom/base",
    "//url/mojom:url_mojom_gurl",
  ]

  webui_module_path = "/"
}
